//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Stock
    {
        public string Name { get; set; }
        public string Educational_year { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
