//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Supervisor_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
