//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drive
    {
        public int Bus_ID { get; set; }
        public int Event_ID { get; set; }
        public int Driver_ID { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Event Event { get; set; }
    }
}
