//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Drives = new HashSet<Drive>();
            this.Participants = new HashSet<Participant>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Is_visit { get; set; }
        public string Name { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Participants_No { get; set; }
        public Nullable<int> Supervisor_ID { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drive> Drives { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Non_Visit Non_Visit { get; set; }
        public virtual Visit Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
