//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_Login
    {
        public int U_ID { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public string UserName { get; set; }
    }
}
